import fs from "fs";
import path from "path";

const REPORTS_DIR = path.join(__dirname_or_cwd(), "reports");

function __dirname_or_cwd() {
  return process.cwd();
}

/**
 * Generates both HTML and Markdown Test Execution Reports.
 */
export function generateTestReport(suiteResults) {
  if (!fs.existsSync(REPORTS_DIR)) {
    fs.mkdirSync(REPORTS_DIR, { recursive: true });
  }

  const timestamp = new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" });
  const total = suiteResults.length;
  const passed = suiteResults.filter(r => r.passed).length;
  const failed = total - passed;
  const passPercentage = total > 0 ? ((passed / total) * 100).toFixed(1) : "0.0";

  // 1. Generate Markdown Report
  const mdContent = `
# KhetAI Test Execution Report — Integrated AI, Data-Driven & Keyword-Driven Pipeline

**Execution Time**: ${timestamp}  
**Testing Framework**: Vitest + Supertest + Custom Keyword Engine  
**Overall Status**: ${failed === 0 ? "🟢 ALL TESTS PASSED" : "🔴 TESTS FAILED"}  

---

## Executive Summary

| Metric | Count | Percentage |
|---|---|---|
| **Total Test Cases** | **${total}** | 100% |
| **Passed** | <span style="color:green">**${passed}**</span> | ${passPercentage}% |
| **Failed** | <span style="color:red">**${failed}**</span> | ${(100 - passPercentage).toFixed(1)}% |
| **Skipped** | 0 | 0% |

---

## Integrated Architecture Workflow

\`\`\`
      AI SYNTHETIC DATA GENERATOR (AI Prompt / Synthesizer)
                              ↓
      EXTERNAL TEST DATA FILES (CSV / JSON Datasets)
                              ↓
            DATA-DRIVEN TEST RUNNER (Iterative Loop)
                              ↓
            KEYWORD-DRIVEN LAYER (Reusable Keywords)
                              ↓
          KHETAI APPLICATION (FAO-56 Engine / Express API)
                              ↓
              VALIDATION ASSERTIONS (Vitest Expect)
                              ↓
                 TEST REPORT (HTML / Markdown)
\`\`\`

---

## Detailed Test Case Execution Results

| Test Case ID | Category | Keywords Used | Expected Result | Actual Result | Status |
|---|---|---|---|---|---|
${suiteResults.map(r => `| \`${r.testCaseId}\` | ${r.category || "Integration"} | \`${r.keywordsUsed}\` | ${r.expectedResult} | ${r.actualResult} | ${r.passed ? "✅ PASS" : "❌ FAIL"} |`).join("\n")}

---

## Failure Details

${failed === 0 ? "*No test failures recorded.*" : suiteResults.filter(r => !r.passed).map(r => `### ${r.testCaseId}\n- **Reason**: ${r.failureReason}\n- **Details**: ${JSON.stringify(r.details || {})}`).join("\n\n")}

---

*Report auto-generated by KhetAI Automated Test Harness.*
`;

  const mdPath = path.join(REPORTS_DIR, "TEST_EXECUTION_REPORT.md");
  fs.writeFileSync(mdPath, mdContent.trim(), "utf8");

  // 2. Generate Modern HTML Report
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>KhetAI - Test Execution Report</title>
  <style>
    :root {
      --primary: #10b981;
      --primary-dark: #059669;
      --bg: #0f172a;
      --card-bg: #1e293b;
      --text: #f8fafc;
      --text-muted: #94a3b8;
      --border: #334155;
      --pass: #22c55e;
      --fail: #ef4444;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background-color: var(--bg);
      color: var(--text);
      margin: 0;
      padding: 30px;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding-bottom: 20px;
      border-bottom: 1px solid var(--border);
    }
    .title { font-size: 28px; font-weight: 700; color: #34d399; margin: 0; }
    .subtitle { color: var(--text-muted); font-size: 14px; margin-top: 5px; }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 20px;
      margin: 30px 0;
    }
    .stat-card {
      background-color: var(--card-bg);
      padding: 20px;
      border-radius: 12px;
      border: 1px solid var(--border);
      text-align: center;
    }
    .stat-value { font-size: 36px; font-weight: 800; }
    .stat-label { color: var(--text-muted); font-size: 13px; text-transform: uppercase; margin-top: 5px; }
    .val-total { color: #60a5fa; }
    .val-pass { color: var(--pass); }
    .val-fail { color: var(--fail); }
    .val-rate { color: #f59e0b; }
    table {
      width: 100%;
      border-collapse: collapse;
      background: var(--card-bg);
      border-radius: 12px;
      overflow: hidden;
      border: 1px solid var(--border);
    }
    th, td {
      padding: 14px 18px;
      text-align: left;
      border-bottom: 1px solid var(--border);
    }
    th { background: #0f172a; color: var(--text-muted); font-size: 13px; text-transform: uppercase; }
    tr:hover { background: #26334d; }
    .badge {
      padding: 4px 10px;
      border-radius: 20px;
      font-size: 12px;
      font-weight: 600;
    }
    .badge-pass { background: rgba(34, 197, 94, 0.2); color: var(--pass); }
    .badge-fail { background: rgba(239, 68, 68, 0.2); color: var(--fail); }
    .code { font-family: monospace; font-size: 13px; background: rgba(255,255,255,0.06); padding: 2px 6px; border-radius: 4px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div>
        <h1 class="title">🌱 KhetAI Test Execution Report</h1>
        <div class="subtitle">Keyword-Driven + Data-Driven + AI Synthetic Test Automation Suite</div>
      </div>
      <div style="text-align: right; color: var(--text-muted); font-size: 13px;">
        Generated: ${timestamp}
      </div>
    </div>

    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-value val-total">${total}</div>
        <div class="stat-label">Total Test Cases</div>
      </div>
      <div class="stat-card">
        <div class="stat-value val-pass">${passed}</div>
        <div class="stat-label">Passed</div>
      </div>
      <div class="stat-card">
        <div class="stat-value val-fail">${failed}</div>
        <div class="stat-label">Failed</div>
      </div>
      <div class="stat-card">
        <div class="stat-value val-rate">${passPercentage}%</div>
        <div class="stat-label">Pass Rate</div>
      </div>
    </div>

    <h2>Test Execution Details</h2>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Category</th>
          <th>Keywords Used</th>
          <th>Expected Result</th>
          <th>Actual Result</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        ${suiteResults.map(r => `
        <tr>
          <td class="code">${r.testCaseId}</td>
          <td>${r.category || "Integrated Pipeline"}</td>
          <td class="code">${r.keywordsUsed}</td>
          <td>${r.expectedResult}</td>
          <td>${r.actualResult}</td>
          <td><span class="badge ${r.passed ? 'badge-pass' : 'badge-fail'}">${r.passed ? 'PASS' : 'FAIL'}</span></td>
        </tr>
        `).join("")}
      </tbody>
    </table>
  </div>
</body>
</html>`;

  const htmlPath = path.join(REPORTS_DIR, "test-execution-report.html");
  fs.writeFileSync(htmlPath, htmlContent.trim(), "utf8");

  console.log(`[Report Generator] Generated Markdown Report -> ${mdPath}`);
  console.log(`[Report Generator] Generated HTML Report     -> ${htmlPath}`);

  return { mdPath, htmlPath };
}
